backend:
  name: github
  repo: pattern-buildings/website

local_backend: true

site_url: https://patternbuildings.com
display_url: patternbuildings.com
logo_url: https://
show_preview_links: false

media_folder: "_data/uploads"
media_library:
  name: cloudinary
  config:
    cloud_name: patternbuildings
    api_key: 146329144562262

collections:
  - name: "posts"
    label: "Posts"
    label_singular: 'Post'
    folder: "_data/posts"
    create: true
    slug: "{{order}}-{{slug}}"
    summary: '{{title}} -- #{{order}}'
    sortableFields: ['title', 'order']
    editor:
     preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Manual PDF", name: "manual_pdf", widget: "file"}
      - {label: "Order", name: "order", widget: "number", default: 0, valueType: "int"}

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - name: 'home-settings'
        label: 'Home settings'
        file: '_data/settings/home-settings.yml'
        description: 'Setup fields for home page'
        fields:
          - name: features
            label: Features
            label_singular: 'Feature'
            widget: list
            collapsed: true
            minimize_collapsed: false
            summary: '{{fields.name}} - {{fields.description}}'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown', minimal: true, buttons: [], editorComponents: [] }
