backend:
  name: github
  repo: pattern-buildings/website

publish_mode: editorial_workflow
local_backend: true

site_url: https://patternbuildings.com
display_url: patternbuildings.com
show_preview_links: false

media_folder: "_data/uploads"
media_library:
  name: cloudinary
  config:
    cloud_name: patternbuildings
    api_key: 146329144562262

collections:

  - name: "projects"
    label: "Projects"
    label_singular: 'Project'
    folder: "_data/projects"
    create: true
    slug: "{{title}}"
    summary: '#{{order}} - {{title}}'
    sortableFields: ['title', 'order']
    editor:
      preview: false
    fields:
      - {label: "Cover image", name: "cover", widget: "image"}
      - {label: "Title", name: "title", widget: "string", hint: "Also used as a slug"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Order", name: "order", widget: "number", default: 0, valueType: "int"}
      - {label: "Featured on home page", name: "featured", widget: "boolean", default: false}
      - name: facts
        label: Facts
        label_singular: item
        widget: list
        fields:
          - {label: Key, name: key, widget: string}
          - {label: Value, name: value, widget: string}
      - label: "CTA"
        name: "cta"
        widget: "object"
        fields: 
          - {label: URL, name: url, widget: string, required: false}
          - {label: Label, name: label, widget: string, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: downloads
        label: Downloads
        label_singular: 'Download'
        widget: list
        collapsed: true
        minimize_collapsed: false
        summary: '{{title}} - {{type}}'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {label: "File", name: "file", widget: "file", required: false}
          - {label: "URL", name: "url", widget: "string", required: false}
          - label: "Type"
            name: "type"
            widget: "select"
            options: ["pdf", "cad", 'other']

  # ============================================================================

  - name: "docs"
    label: "Docs"
    label_singular: 'Doc'
    folder: "_data/docs"
    create: true
    slug: "{{title}}"
    summary: '#{{order}} - {{title}}'
    sortableFields: ['title', 'order']
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Also used as a slug"}
      - {label: "Order", name: "order", widget: "number", default: 0, valueType: "int"}
      - {label: "Is subarticle?", name: "is_subcarticle", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # ============================================================================

  - name: "downloads"
    label: "Downloads"
    label_singular: 'Download'
    folder: "_data/downloads"
    create: true
    slug: "{{title}}"
    summary: '#{{order}} - {{title}}'
    sortableFields: ['title', 'order']
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Also used as a slug"}
      - {label: "Order", name: "order", widget: "number", default: 0, valueType: "int"}
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["pdf", "cad", 'other']
      - {label: "File", name: "file", widget: "file", required: false}
      - {label: "URL", name: "url", widget: "string", required: false}

  # ============================================================================

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:

      - name: 'discover-settings'
        label: 'Discover settings (RED)'
        file: '_data/settings/discover-settings.yml'
        description: 'Setup fields for home page'
        fields:
          - {label: "Idea", name: "idea", widget: "markdown"}
          - name: facts
            label: Facts
            label_singular: item
            widget: list
            fields:
              - {label: Key, name: key, widget: string}
              - {label: Value, name: value, widget: string}
          - name: features
            label: Features
            label_singular: 'Feature'
            widget: list
            collapsed: true
            minimize_collapsed: false
            summary: '{{fields.name}} - {{fields.description}}'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown', minimal: true, buttons: [], editorComponents: [] }
          - {label: "Intro for projects", name: "intro_projects", widget: "markdown"}
          - name: supporters
            label: Supporters
            label_singular: 'Supporter'
            widget: list
            collapsed: true
            minimize_collapsed: false
            fields:
              - {label: "Logo", name: "logo", widget: "file"}
              - { label: 'URL', name: 'url', widget: 'string', required: false }
          - name: core_team
            label: Core team
            label_singular: 'Team member'
            widget: list
            collapsed: true
            minimize_collapsed: false
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Responsibility', name: 'responsibility', widget: 'string' }
              - { label: "Avatar", name: "avatar", widget: "file" }
              - { label: 'URL', name: 'url', widget: 'string', required: false }
          - name: contributors
            label: Contributors
            label_singular: 'Contributor'
            widget: list
            collapsed: true
            minimize_collapsed: false
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Responsibility', name: 'responsibility', widget: 'string' }
              - { label: "Avatar", name: "avatar", widget: "file" }
              - { label: 'URL', name: 'url', widget: 'string', required: false }
          - { label: "License desctiption", name: "license_description", widget: "markdown"}
          - { label: 'License URL', name: 'license_url', widget: 'string' }

      - name: 'learn-settings'
        label: 'Learn settings (GREEN)'
        file: '_data/settings/learn-settings.yml'
        description: 'Setup fields for docs'
        fields:
          - {label: "Intro for docs", name: "intro_docs", widget: "markdown"}
          
      - name: 'engage-settings'
        label: 'Engage settings (BLUE)'
        file: '_data/settings/engage-settings.yml'
        description: 'Setup fields for engage section'
        fields:
          - {label: "Intro for Become a supporter", name: "intro_supporter", widget: "markdown"}
          - {label: "Intro for Become a contributor", name: "intro_contributor", widget: "markdown"}
          - {label: "Intro for Contact the team", name: "intro_team", widget: "markdown"}
          - {label: "Intro for downloads", name: "intro_downloads", widget: "markdown"}
          
      - name: 'workshop-settings'
        label: 'Workshop settings'
        file: '_data/settings/workshop-settings.yml'
        description: 'All infromation related to the workshop'
        fields:
          - {label: "Content", name: "content", widget: "markdown"}
          
      - name: 'navigation'
        label: 'Navigation'
        file: '_data/settings/navigation.yml'
        description: 'Configure the navigation panel'
        fields:
          - name: discover
            label: Discover
            label_singular: 'item'
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'url', name: 'url', widget: 'string' }
              - { label: 'icon', name: 'icon', widget: 'select', hint: 'ask Ilya to if you need more icons ;D', options: [  mdiHomeOutline, mdiInformationOutline, mdiCardsVariant, mdiHeartOutline, mdiAccountMultipleOutline, mdiLicense, mdiFileDocumentOutline, mdiCubeOutline, mdiDrawing, mdiCommentQuestionOutline, mdiHeartPlusOutline, mdiAccountPlusOutline, mdiEmailOutline, mdiDownloadOutline, mdiTools ] }
              - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false }
          
          - name: learn
            label: Learn
            label_singular: 'item'
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'url', name: 'url', widget: 'string' }
              - { label: 'icon', name: 'icon', widget: 'select', hint: 'ask Ilya to if you need more icons ;D', options: [  mdiHomeOutline, mdiInformationOutline, mdiCardsVariant, mdiHeartOutline, mdiAccountMultipleOutline, mdiLicense, mdiFileDocumentOutline, mdiCubeOutline, mdiDrawing, mdiCommentQuestionOutline, mdiHeartPlusOutline, mdiAccountPlusOutline, mdiEmailOutline, mdiDownloadOutline, mdiTools ] }
              - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false }
          
          - name: engage
            label: Engage
            label_singular: 'item'
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'url', name: 'url', widget: 'string' }
              - { label: 'icon', name: 'icon', widget: 'select', hint: 'ask Ilya to if you need more icons ;D', options: [  mdiHomeOutline, mdiInformationOutline, mdiCardsVariant, mdiHeartOutline, mdiAccountMultipleOutline, mdiLicense, mdiFileDocumentOutline, mdiCubeOutline, mdiDrawing, mdiCommentQuestionOutline, mdiHeartPlusOutline, mdiAccountPlusOutline, mdiEmailOutline, mdiDownloadOutline, mdiTools ] }
              - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false }

  # ============================================================================