backend:
  name: github
  repo: pattern-buildings/website

media_library:
  name: cloudinary
  config:
    cloud_name: patternbuildings
    api_key: 146329144562262

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}