backend:
  name: github
  repo: pattern-buildings/website

site_url: https://patternbuildings.com

media_library:
  name: cloudinary
  config:
    cloud_name: patternbuildings
    api_key: 146329144562262

collections:
  - name: "posts"
    label: "Posts"
    label_singular: 'Post'
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - name: 'home-settings'
        label: 'Home settings'
        file: '_data/home-settings.yml'
        description: 'Setup fields for home page'
        fields:
          - name: features
            label: Features
            label_singular: 'Feature'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string', hint: 'Keep it short' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
