title: Garage48 Future of Wood 2020
subtitle: Join the hands-on and on-site 48h event in Tartu. Design and build
  your Pattern Building and win funding for further development.
cta: Learn more
url: https://garage48.org/events/garage48-future-of-wood-2020
image: https://res.cloudinary.com/patternbuildings/image/upload/v1603358313/News/w1_mprfao.png
hide: false
