title: Garage48 Future of Wood 2020
subtitle: Prototype your mass-custom house type and win funding for further
  development. Join the hands-on and on-site 48h event in Tartu 13.-15. November
cta: Learn more
url: https://garage48.org/events/garage48-future-of-wood-2020
image: https://res.cloudinary.com/patternbuildings/image/upload/v1603358313/News/w1_mprfao.png
hide: false
