title: Workshop announcement
subtitle: Some additional text about it
cta: Learn more
url: https://patternbuildings.com
image: https://res.cloudinary.com/patternbuildings/image/upload/v1592836328/pb-logo_v1vqwj.jpg
hide: false
