idea: >-
  369 Pattern Buildings is an **industrial construction system** based on
  **modular design** for creating up to **7** floor **wooden buildings** of
  different typology and appearance. It is fit for designing and constructing
  buildings with a clear span of up to 8.5 m. A Pattern building can be a
  **house, office, school, kindergarten, hospital** etc. The 369 system has 3
  basic module sizes - M3, M6, and M9.


  Every Pattern Building is: 


  * mass-customisable; 

  * environmentally friendly;

  * made primarily of timber; 

  * modular and prefabricated;

  * ready to be produced, assembled, and transported in most European countries
facts:
  - key: Material
    value: Hybrid timber, LVL
  - key: Size
    value: 1-7 floors
  - key: Type
    value: housing, offices, hospitals etc
  - key: Construction method
    value: Offsite modular
features:
  - name: Informative
    description: The 369 Pattern Building architecture must be informative. Its
      constructive and technical structure must be easily readable by the
      builder, the user and the maintainer of the building.
  - name: Universal
    description: The 369 Pattern Building must be simple enough for it to be
      produced at different factories and assembled by different builders. The
      transport of modules must be legally and technically possible without
      special permits or escort to all regions of Europe by road, rail and
      water.
  - name: Environment friendly
    description: The 369 Pattern Building needs a minimal amount of energy for
      production, transport and operation.
  - name: Re-configurable
    description: The components of 369 Pattern Building are easily accessible for
      disassembling and upgrading.
  - name: Durable
    description: Given the growth cycle of wood used in construction, the main
      structures of the building must last for at least 100 years.
  - name: Adaptable
    description: The modular system should not constrain design freedom and can be
      adapted to different typologies, providing only the technical means for
      achieving the design goals.
  - name: Open
    description: The 369 Pattern Building concept remains available without
      restrictions (see License) to anyone who wishes to develop it further.
  - name: Autonomous
    description: Functional units of the building (for example, apartments in the
      case of an apartment building) should be independent of each other both in
      terms of access and in terms of utility systems.
intro_projects: "List of projects that use **369 Pattern Buildings** open-source
  system. A Pattern building can be a house, office, school, kindergarten,
  hospital etc. Every Pattern Building is: mass-customisable; environmentally
  friendly; made primarily of wood; modular and prefabricated; ready to be
  produced, assembled, and transported in most European countries."
supporters:
  - logo: https://res.cloudinary.com/patternbuildings/image/upload/v1594733185/supporters/estonian-academy-arts-logo_c0a1f5b2_x2ppju.svg
    url: https://www.artun.ee/en/home/
  - logo: https://res.cloudinary.com/patternbuildings/image/upload/v1597311278/supporters/harnet_logo_fdkzc4.svg
    url: https://www.harmet.ee/?lang=en
  - logo: https://res.cloudinary.com/patternbuildings/image/upload/v1597246379/supporters/Creatomus_white_back_zjizcf.png
    url: https://creatomus.com
  - logo: https://res.cloudinary.com/patternbuildings/image/upload/v1597311431/supporters/THORN_ENGINEERING_fkvmi6.png
core_team:
  - name: Renee Puusepp
    responsibility: Lead architect
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247022/core%20team/Renee_2019_1_wvpazo.png
    url: https://www.linkedin.com/in/reneepuusepp/
  - name: Egle Vogt
    responsibility: Lead system engineer
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247223/core%20team/EgleVogt_keazaa.jpg
  - name: Eero Tuhkanen
    responsibility: Lead structural engineer
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247369/core%20team/EeroTuhkanen_lyigrs.jpg
  - name: Kristo Kalbe
    responsibility: HVAC and energy engineer
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247372/core%20team/KristoKalbe_gj02ok.jpg
  - name: Lauri Läänelaid
    responsibility: Architect
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247792/core%20team/Lauri_La%CC%88a%CC%88nelaid_bdxalq.png
  - name: Marianna Zvereva
    responsibility: Architect
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247801/core%20team/Profile_temp_aag67g.png
  - name: Vitali Valtanen
    responsibility: BIM manager and designer
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597938593/core%20team/Vitali_Valtanen_2_duwadt.jpg
  - name: Keiti Lige
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247801/core%20team/Profile_temp_aag67g.png
    responsibility: Architect
  - name: Triin Valner
    responsibility: Architect
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247801/core%20team/Profile_temp_aag67g.png
  - name: Kiur Lootus
    responsibility: Architect and tutor
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247801/core%20team/Profile_temp_aag67g.png
contributors:
  - name: Johannes Madis Aasmäe
    responsibility: Architect
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247796/core%20team/Johannes_Aasma%CC%88e_exuzwz.png
    url: ""
  - name: Taavi Lõoke
    responsibility: Architect
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597248171/core%20team/Taavi_Lo%CC%83oke_zgqnbi.jpg
  - name: Inke Brett Eek
    responsibility: Architect
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247801/core%20team/Profile_temp_aag67g.png
  - name: Ilya Vasilyev
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597311729/contributors/IV_jtt9e7.jpg
    responsibility: Web designer
    url: https://ilya.aivi.dev/
  - name: Vello Laanemaa
    responsibility: Designer
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247801/core%20team/Profile_temp_aag67g.png
  - name: Nomad architects
    responsibility: Architects
    url: nomadarchitects.lv
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597248703/core%20team/Screen_Shot_2020-08-12_at_19.09.57_vn6zcv.png
  - name: Julia Pupsheva
    responsibility: Structural engineer
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1597247801/core%20team/Profile_temp_aag67g.png
license_description: 369 Pattern Buildings by Renee Puusepp, Egle Vogt, Lauri
  Läänelaid, Marianna Zvereva, Eero Tuhkanen, Kristo Kalbe is licensed under
  **CC BY 4.0**
license_url: https://creativecommons.org/licenses/by/4.0/
