idea: >-
  Pattern Building is an **industrial construction system** based on **modular
  design** for creating up to **7** floor buildings of different typology and
  appearance. It is fit for designing and constructing buildings with clear span
  of up to 8.5 m. A Pattern building can be a **house, office, school,
  kindergarten, hospital** etc. 


  Every Pattern Building is: 


  * mass-customisable; 

  * environmentally friendly;

  * made primarily of wood; 

  * modular and prefabricated;

  * ready to be produced, assembled, and transported in most European countries;
facts:
  - key: Material
    value: Hybrid timber, LVL
  - key: Size
    value: 1-7 floors
  - key: Type
    value: housing, offices, hospitals etc
  - key: Construction method
    value: Offsite modular
features:
  - name: Informative
    description: The Pattern Building architecture must be informative. Its
      constructive and technical structure must be easily readable by the
      builder, the user and the maintainer of the building.
  - name: Universal
    description: The Pattern Building must be simple enough for it to be produced at
      different factories and assembled by different builders. The transport of
      modules must be legally and technically possible without special permits
      or escort to all regions of Europe by road, rail and water.
  - name: Environment friendly
    description: The Pattern Building needs a minimal amount of energy for
      production, transport and operation.
  - name: Re-configurable
    description: The components of Pattern Building are easily accessible for
      disassembling and upgrading.
  - name: Durable
    description: Given the growth cycle of wood used in construction, the main
      structures of the building must last for at least 100 years.
  - name: Adaptable
    description: The modular system should not constrain design freedom and can be
      adapted to different typologies, providing only the technical means for
      achieving the design goals.
  - name: Open
    description: The Pattern Building concept remains available without restrictions
      (see License) to anyone who wishes to develop it further.
  - name: Autonomous
    description: Functional units of the building (for example, apartments in the
      case of an apartment building) should be independent of each other both in
      terms of access and in terms of utility systems.
intro_projects: "List of projects that use **Pattern Buildings** open-source
  system. A Pattern building can be a house, office, school, kindergarten,
  hospital etc. Every Pattern Building is: mass-customisable; environmentally
  friendly; made primarily of wood; modular and prefabricated; ready to be
  produced, assembled, and transported in most European countries."
supporters:
  - logo: https://res.cloudinary.com/patternbuildings/image/upload/v1594733185/supporters/estonian-academy-arts-logo_c0a1f5b2_x2ppju.svg
    url: https://www.artun.ee/en/home/
  - logo: https://res.cloudinary.com/patternbuildings/image/upload/v1594733185/supporters/estonian-academy-arts-logo_c0a1f5b2_x2ppju.png
    url: https://www.artun.ee/en/home/
  - logo: https://res.cloudinary.com/patternbuildings/image/upload/v1594733185/supporters/estonian-academy-arts-logo_c0a1f5b2_x2ppju.png
    url: https://www.artun.ee/en/home/
core_team:
  - name: Core Team Name
    responsibility: responsibility
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1592836328/pb-logo_v1vqwj.jpg
    url: https://google.com
contributors:
  - name: Contributor Name
    responsibility: contributor responsibility
    avatar: https://res.cloudinary.com/patternbuildings/image/upload/v1592836328/pb-logo_v1vqwj.jpg
    url: https://google.com
license_description: Pattern Buildings by Renee Puusepp, Egle Vogt, Lauri
  Läänelaid, Marianna Zvereva, Eero Tuhkanen, Kristo Kalbe is licensed under
  **CC BY 4.0**
license_url: https://creativecommons.org/licenses/by/4.0/
