intro_supporter: We rely on our supporters to keep the project moving forward.
  If you want to become a supporter please fill the form below. We really
  appreciate any form of help.
intro_contributor: We will be happy to see you as part of our team, just fill
  the form below and we'll be in touch.
intro_team: If you have any questions about the system you can fill the form
  below to connect with the team.
intro_downloads: Here you find the downloadable files to support architects,
  engineers and manufacturers of Pattern Buildings.
