intro_supporter: We rely on our supporters to keep the project moving forward.
  If you want to become a supporter please fill the form below. We really
  appreciate any form of help.
intro_contributor: We will be happy to see you as part of our team, just fill
  the form below and we'll be in touch.
intro_team: If you have any questions about the system you can fill the form
  below to connect with the team.
intro_downloads: >-
  **Pattern Building 369** is an industrial construction system based on modular
  design for creating up to 7 floor buildings of different typology and
  appearance. It is fit for designing and constructing buildings with clear span
  of up to 8.5 m. A Pattern building  can be a house, office, school,
  kindergarten, hospital etc. 


  Every Pattern Building is: mass-customisable; environmentally friendly; made primarily of wood;  modular and prefabricated; ready to be produced, assembled, and transported in most European countries.
