idea: >-
  Pattern Building is an industrial construction system based on modular design
  for creating up to 7 floor buildings of different typology and appearance. It
  is fit for designing and constructing buildings of up to 8.5m clear span -
  this means housing, offices, schools, kindergartens, hospitals etc. 


  Every Pattern Building is:

  mass-customizable;environmentally friendly;

  made primarily of wood;

  modular;

  ready to be produced, assembled, and transported in most European countries.
facts:
  - key: key1
    value: value 1
  - key: key2
    value: value 2
  - key: hello
    value: world
features:
  - name: Informative
    description: The Pattern Building architecture must be informative. Its
      constructive and technical structure must be easily readable by the
      builder, the user and the maintainer of the building.
  - name: Universal
    description: The Pattern Building must be simple enough for it to be produced at
      different factories and assembled by different builders. The transport of
      modules must be legally and technically possible without special permits
      or escort to all regions of Europe by road, rail and water.
  - name: Environment friendly
    description: The Pattern Building needs a minimal amount of energy for
      production, transport and operation.
  - name: Re-configurable
    description: The components of Pattern Building are easily accessible for
      disassembling and upgrading.
  - name: Durable
    description: Given the growth cycle of wood used in construction, the main
      structures of the building must last for at least 100 years.
  - name: Adaptable
    description: The modular system should not constrain design freedom and can be
      adapted to different typologies, providing only the technical means for
      achieving the design goals.
  - name: Open
    description: The Pattern Building concept remains available without restrictions
      (see License) to anyone who wishes to develop it further.
  - name: Autonomous
    description: Functional units of the building (for example, apartments in the
      case of an apartment building) should be independent of each other both in
      terms of access and in terms of utility systems.
