intro_docs: >-
  This user manual is intended for architects, engineers and manufacturers. It
  can help you to find detailed information about **369 Pattern Buildings**
  system and learn how to use it.


  If you have a question that is not covered by the documentation, please [let us know](/contact-team/).
