intro_docs: >-
  **Pattern Building** is an industrial construction system based on modular
  design for creating up to 7 floor wooden buildings of different typology and
  appearance. It is fit for designing and constructing buildings with clear span
  of up to 8.5 m. A Pattern building  can be a house, office, school,
  kindergarten, hospital etc. 


  Every Pattern Building is: mass-customisable; environmentally friendly; made primarily of wood;  modular and prefabricated; ready to be produced, assembled, and transported in most European countries.
